# Generated by Django 3.0.3 on 2020-02-17 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormeMot',
            fields=[
                ('MotID', models.AutoField(primary_key=True, serialize=False)),
                ('Mot', models.CharField(max_length=50)),
                ('Infos', models.TextField(max_length=250)),
            ],
            options={
                'verbose_name': 'Mots Formé',
            },
        ),
        migrations.CreateModel(
            name='Mot',
            fields=[
                ('MotID', models.AutoField(primary_key=True, serialize=False)),
                ('Mot', models.CharField(max_length=50)),
                ('Table', models.IntegerField()),
                ('Infos', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='TableTransformation',
            fields=[
                ('TransformationID', models.AutoField(primary_key=True, serialize=False)),
                ('NumTab', models.IntegerField()),
                ('Terminaison', models.CharField(max_length=10, null=True)),
                ('Transformation', models.CharField(max_length=10)),
                ('Infos', models.TextField(max_length=100)),
            ],
        ),
    ]
