# Generated by Django 3.0.3 on 2020-02-15 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_delete_utilisateur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('UtilID', models.AutoField(primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=50)),
                ('Prenom', models.CharField(max_length=50)),
                ('MdP', models.CharField(max_length=50)),
                ('Droit', models.IntegerField(default=0)),
            ],
        ),
    ]
