# Generated by Django 3.0.3 on 2020-02-17 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_utilisateur'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Utilisateur',
        ),
    ]
